- name: CREATE BIG-IP
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

  - name: CREATE ANSIBLE CFT DEPLOYMENT
    cloudformation:
      stack_name: "{{ stack_name }}"
      state: present
      region: "{{ aws_region }}"
      disable_rollback: true
      template_url: "{{ template_url }}"
      template_parameters:
        group:  "{{ group }}"
        declarationUrl:  "{{ declarationUrl }}"
        Vpc: "{{ vpc_id }}"
        managementSubnetAz1:  "{{ managementSubnetAz1 }}"
        subnet1Az1:  "{{ subnet1Az1 }}"
        restrictedSrcAddress: "{{ restrictedSrcAddress }}"
        restrictedSrcAddressApp: "{{ restrictedSrcAddressApp }}"
        sshKey:  "{{ sshKey }}"
        environment:  "{{ environment }}"
        application:  "{{ application }}"
        customImageId:  "{{ customImageId }}"
        imageName:  "{{ imageName }}"
        ntpServer:  "{{ ntpServer }}"
        costcenter:  "{{ costcenter }}"
        owner:  "{{ uk_se_name }}"
        timezone:  "{{ timezone }}"
        instanceType:  "{{ instanceType }}"
        allowUsageAnalytics:  "{{ allowUsageAnalytics }}"
      tags:
        automated: "{{ automation_tool }}"
        stack: "{{ stack_name }}"
        UK-SE: "{{ uk_se_name }}"
    register: result 
